# Generated by Django 4.2.7 on 2023-12-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
